style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/logleads/LogverzCore
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - fix
      - update
      - perf
      - refactor
      - build
      - chore
      - polish
    title_maps:
      feat: âœ¨ Features
      fix: ğŸ› Bug Fixes
      perf: âš¡ Performance Improvements
      refactor: â™»ï¸ Code Refactoring
      update: ğŸ”„ Updates
      build: ğŸ‘· Building scripts changes
      chore: ğŸ§¹ Other changes
      polish: ğŸ’… Style changes
      # other images https://gitmoji.dev/
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE